### ISSUE TITLE
use StatsProvider service property "type" for counting processors

### ISSUE THREAD

**Issue by slintes** [INAETICS/kubernetes-demo-cluster#13]
celix processor is not exporting any interface, while felix does (even while the interface is empty)

**Comment by slintes** [comment]
updated viewer for this (INAETICS/demonstrator@5b52dcc0f6e965ab94924392b8c27813f7737a8a)
@bpetri: please close this when you updated the celix processor

**Comment by bpetri** [comment]
celix processor and wiring topology manager updated in INAETICS/node-provisioning@eb9f3daa6f6c1a4213ca82e2a7d94ab1e8c67ce9
