### ISSUE TITLE
System information about Processor/Producer disappears

### ISSUE THREAD

**Issue by bpetri** [INAETICS/kubernetes-demo-cluster#8]
System information about Processor/Producers is only shown for a short period and disappears afterwards:

![screenshot from 2015-09-08 10 25 15](https://cloud.githubusercontent.com/assets/8858685/9730014/faac259c-5613-11e5-9435-f06d7e24f9de.png)

**Comment by slintes** [comment]
I never had that problem. Can you please add the osgi log of the viewer when this happens again? Thanks

**Comment by slintes** [comment]
not reproducable anymore after updating everything
